# Generated by Django 5.1.2 on 2025-11-14 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.PositiveIntegerField(unique=True, verbose_name='День')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
            ],
            options={
                'verbose_name': 'День курса',
                'verbose_name_plural': 'Дни курса',
                'db_table': 'course_days',
                'ordering': ('day_number',),
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='QuizResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('energy', models.PositiveSmallIntegerField(verbose_name='Энергия')),
                ('happiness', models.PositiveSmallIntegerField(verbose_name='Счастье')),
                ('sleep_quality', models.PositiveSmallIntegerField(verbose_name='Сон')),
                ('relationships_quality', models.PositiveSmallIntegerField(verbose_name='Отношения')),
                ('life_balance', models.PositiveSmallIntegerField(verbose_name='Баланс')),
                ('strategy_level', models.PositiveSmallIntegerField(verbose_name='Стратегия')),
                ('created_at', models.DateTimeField(verbose_name='Создан')),
                ('updated_at', models.DateTimeField(verbose_name='Обновлён')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Результат опроса',
                'verbose_name_plural': 'Результаты опроса',
                'db_table': 'quiz_results',
                'ordering': ('-created_at',),
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(db_index=True, unique=True, verbose_name='Telegram ID')),
                ('username', models.CharField(blank=True, max_length=255, null=True, verbose_name='Никнейм')),
                ('first_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Фамилия')),
                ('language_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='Язык')),
                ('full_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='ФИО')),
                ('role', models.CharField(blank=True, max_length=255, null=True, verbose_name='Должность/роль')),
                ('company', models.CharField(blank=True, max_length=255, null=True, verbose_name='Компания')),
                ('subscription_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='Тип подписки')),
                ('subscription_started_at', models.DateTimeField(blank=True, null=True, verbose_name='Подписка начата')),
                ('subscription_paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Оплата получена')),
                ('consent_accepted_at', models.DateTimeField(blank=True, null=True, verbose_name='Согласие получено')),
                ('created_at', models.DateTimeField(verbose_name='Создан')),
                ('updated_at', models.DateTimeField(verbose_name='Обновлён')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Пользователь Telegram',
                'verbose_name_plural': 'Пользователи Telegram',
                'db_table': 'users',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TouchContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_day', models.ForeignKey(blank=True, db_column='course_day_id', null=True, on_delete=models.DO_NOTHING, related_name='touches', to='dashboard.courseday', verbose_name='День курса')),
                ('touch_type', models.CharField(choices=[('morning', 'Утро'), ('day', 'День'), ('evening', 'Вечер')], max_length=20, verbose_name='Тип касания')),
                ('step_code', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Код шага')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('video_file', models.FileField(blank=True, db_column='video_file_path', null=True, upload_to='touch_videos/', verbose_name='Видео-файл')),
                ('video_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='Ссылка на видео')),
                ('summary', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('transcript', models.TextField(blank=True, null=True, verbose_name='Расшифровка')),
                ('questions', models.TextField(blank=True, null=True, verbose_name='Вопросы (писать через пропуск строки)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('order_index', models.IntegerField(default=0, verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
            ],
            options={
                'verbose_name': 'Контент касания',
                'verbose_name_plural': 'Контент касаний',
                'db_table': 'touch_contents',
                'ordering': ('course_day__day_number', 'touch_type', 'order_index'),
                'managed': True,
            },
        ),
    ]
