# Generated by Django 5.1.2 on 2025-11-14 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quizresult',
            options={'managed': False, 'ordering': ('-created_at',), 'verbose_name': 'Результат опроса', 'verbose_name_plural': 'Результаты опроса'},
        ),
        migrations.AlterModelOptions(
            name='telegramuser',
            options={'managed': False, 'verbose_name': 'Пользователь Telegram', 'verbose_name_plural': 'Пользователи Telegram'},
        ),
    ]
